### ISSUE TITLE
Request: option for selecting your own sort column and sort order

### ISSUE THREAD

**Issue by Crow74** [AuraQ/BootstrapMultiSelectForMendix#3]
This one is a nice to have.  :blush:

**Comment by lindski** [comment]
Ability to control sort order added to the Data Source tab in commit aaf6de9fdb569ff2c77d0c6c449a1dbc9b527952

I will also create a new release and update the widget in the app store.

**Comment by Crow74** [comment]
The new version of the widget generates an error when I open a page that includes the widget.
I don't currently have the time to create a test project for you, but I thought I'd let you know about the error anyway. Maybe you have a simple solution at hand. :blush: 

An error has occurred while handling the request. [User '_____' with session id 'e28008ce-bacd-457c-b24c-060b87317ef9' and roles '_____']

java.lang.NullPointerException: null
	at com.mendix.webui.actions.ActionUtil$.com$mendix$webui$actions$ActionUtil$$hasNoVirtualAttributes(ActionUtil.scala:66)
	at com.mendix.webui.actions.ActionUtil$$anonfun$buildSortMap$1.apply(ActionUtil.scala:42)
	at com.mendix.webui.actions.ActionUtil$$anonfun$buildSortMap$1.apply(ActionUtil.scala:39)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at com.mendix.webui.actions.ActionUtil$.buildSortMap(ActionUtil.scala:39)
	at com.mendix.webui.actions.ActionUtil$.buildSortMap(ActionUtil.scala:32)
	at com.mendix.webui.actions.ActionUtil$.addSortExpressions(ActionUtil.scala:160)
	at com.mendix.webui.actions.client.XPathRetriever.retrieveWithoutSchema(XPathRetriever.scala:144)
	at com.mendix.webui.actions.client.RetrieveByXPathAction.execute(RetrieveByXPathAction.scala:39)
	at com.mendix.webui.requesthandling.ClientRequestHandler$$anonfun$handleRequest$1.apply$mcV$sp(ClientRequestHandler.scala:322)
	at com.mendix.webui.requesthandling.ClientRequestHandler$$anonfun$handleRequest$1.apply(ClientRequestHandler.scala:315)
	at com.mendix.webui.requesthandling.ClientRequestHandler$$anonfun$handleRequest$1.apply(ClientRequestHandler.scala:315)
	at com.mendix.core.session.Worker$$anonfun$receive$3$$anonfun$2$$anon$1.execute(ActionDispatching.scala:145)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
	at com.mendix.core.session.Worker$$anonfun$receive$3$$anonfun$2.apply(ActionDispatching.scala:147)
	at scala.util.Try$.apply(Try.scala:191)
	at com.mendix.core.session.Worker$$anonfun$receive$3.applyOrElse(ActionDispatching.scala:141)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at com.mendix.core.session.Worker.aroundReceive(ActionDispatching.scala:137)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by lindski** [comment]
I'm not able to reproduce this. Can you try clearing your browser cache and see if that resolves things?

If you are able to provide a sample project that demonstrates the issue I'd be happy to take a look.
